### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by tensor2023** [AxelElaldi/e3so3_conv#2]
Hallo,I found your idea very nice.However, I have a question regarding your method. Did you normalize the input MRI images? If not, how did you deal with the large values (around 20,000) of the original MRI images? Would they affect the gradient backpropagation results? Also, what is the range of values for your FOD?

I would appreciate it if you could answer my questions. Thank you for your time and attention.

**Comment by neel-dey** [comment]
The diffusion volumes are all divided by the per-voxel B0 intensity, after which the tissue response function is computed and training begins. If there are multiple B0s, they are first averaged and that is then used to normalize. There's some related discussion here #1 

We should have put that detail in the main paper and not buried inside the appendix :)
